TuranicTeam/Altay

- README.md
this just optimizes the README and clears language mistakes
> Fixed grammar and typos in README

- src/pocketmine/Player.php
- src/pocketmine/entity/Animal.php
- src/pocketmine/entity/Entity.php
- src/pocketmine/entity/Vehicle.php
- src/pocketmine/entity/hostile/Creeper.php
- src/pocketmine/entity/object/ArmorStand.php
- src/pocketmine/entity/passive/Cow.php
- src/pocketmine/entity/passive/Mooshroom.php
- src/pocketmine/entity/passive/Pig.php
- src/pocketmine/entity/passive/Sheep.php
- src/pocketmine/entity/passive/Villager.php
- src/pocketmine/entity/passive/Wolf.php
Refactor for ArmorStand entity
> Refactor for ArmorStand

- README.md
- src/pocketmine/block/DragonEgg.php
- src/pocketmine/entity/Animal.php
- src/pocketmine/entity/Entity.php
- src/pocketmine/entity/Living.php
- src/pocketmine/entity/Mob.php
- src/pocketmine/entity/Tamable.php
- src/pocketmine/entity/object/LeashKnot.php
- src/pocketmine/item/ItemFactory.php
- src/pocketmine/item/Lead.php
> Leashing Implement

- src/pocketmine/level/Level.php
> Fix for #83

- src/pocketmine/inventory/PlayerOffHandInventory.php
> Fix offhand bug

- src/pocketmine/command/defaults/BanCommand.php
- src/pocketmine/command/defaults/BanIpCommand.php
- src/pocketmine/command/defaults/PardonCommand.php
- src/pocketmine/event/server/AddressBanEvent.php
- src/pocketmine/event/server/BanEvent.php
- src/pocketmine/event/server/UnbanEvent.php
Added API Method for AddressBanEvent, BanEvent and UnbanEvent
I made a few Tests with Plugins using the API to get and Echo data. Everything works fine at the moment
> Added Events for Ban, IP-Ban and Unban

- src/pocketmine/level/Level.php
Added Level::equals() function
nothing
- Added `Level::equals()`
nothing
nothing
nothing
> Level::equals() function

- src/pocketmine/event/block/BlockGrowEvent.php
This can be helpful if you want to change the generated block in a Cobblestone generator
> Implemented setNewState

- src/pocketmine/level/generator/GeneratorManager.php
- src/pocketmine/level/generator/VoidGenerator.php
Emretr1 forgot adding void generator.
Tested, working.
> Added Void Generator

- src/pocketmine/entity/passive/Cat.php
> Fix for cats

- src/pocketmine/entity/Entity.php
* Fixes #166
Plugins will be able to send fake links.
> Using the ID of an entity instead of an entity

- src/pocketmine/entity/object/FireworksRocket.php
> Fixed fireworks

- src/pocketmine/command/defaults/GameRuleCommand.php
- src/pocketmine/level/GameRules.php
I saw that the person (TOWUK) on Discord said that there is no game rule in the software called "immediate respawn". I decided to fix it.
> Implemented "new" gamerule

- src/pocketmine/command/defaults/GameRuleCommand.php
- src/pocketmine/network/mcpe/protocol/types/CommandParameter.php
"Why not?"
There are minor changes in API, you can see them in the commit.
No
This can be tested without additional scripts.
> Updated GameRuleCommand

- src/pocketmine/network/mcpe/protocol/LevelEventPacket.php
Updated LevelEventPacket constants, founded in BDS(1.13.0.34) using IDA.
No.
No.
Yeah, i tested this changes. No code, bc i tested this changes using a very strange... code.
> LevelEventPacket: Founded more constants

- start.sh
rename PocketMine-MP phar file as Altay
> rename PocketMine-MP phar file as Altay

- src/pocketmine/inventory/PlayerUIInventory.php
- src/pocketmine/network/mcpe/protocol/types/UIInventoryOffsets.php
I think this is useful for future work.
No API changes
No perfomance changes
This PR contains only protocol-related changes
I found these values few days ago in latest(1.14.60.5) BDS release. (`View` -> `Open subviews` -> `Enums`)
> Update player's UI-inventory offsets

- src/pocketmine/tile/Furnace.php
Now only takes lava "out of" bucket and leaves bucket behind when furnace burns lava bucket.
> Fixed bucked of lava being taken with bucket.

- src/pocketmine/entity/vehicle/Boat.php
Boat position/rotation updated when player wasn't there before?
Changed that^^^^
Also made sure player won't start flying behind boat by adding a broadcast link function that runs every 100 ticks when the player is in it.
> Boats work again + making sure player stays linked to the boat.

- src/pocketmine/entity/Entity.php
- src/pocketmine/entity/EntityIds.php
- src/pocketmine/network/mcpe/protocol/AddActorPacket.php
Source: https://minecraft.gamepedia.com/Bedrock_Edition_data_value#Entity_IDs
> Added new entity id's

- src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php
> Implement Emotes

- src/pocketmine/item/ItemFactory.php
- src/pocketmine/item/ItemIds.php
- src/pocketmine/item/NetheriteBoots.php
- src/pocketmine/item/NetheriteChestplate.php
- src/pocketmine/item/NetheriteHelmet.php
- src/pocketmine/item/NetheriteHelmeth.php
- src/pocketmine/item/NetheriteLeggings.php
- src/pocketmine/item/TieredTool.php
> Add Netherite items

- src/pocketmine/level/sound/NoteBlockSound.php
fix extradata
FIx noteblockSound
none
> Correct Instrument

- src/pocketmine/Server.php
> Reload folder plugins

- src/pocketmine/entity/projectile/Arrow.php
This PR add ability to pickup arrows to offhand!
Idk
Without API changes.
Without performance changes.
InventoryPickupArrowEvent->getInventory() now maybe return PlayerOffHandInventory
Tested on local server. If you want - I can provide some screenshots.
> Arrow: Pickup to offhand too
